title: Thomasina Lester

name: Thomasina Lester
headline: Incoming Manufacturing Engineer at Procter & Gamble | Industrial Engineering Student at Columbia University
description: >-
  Write an awesome intro and discuss your highlights and qualification. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

profile_image: ./assets/images/profile-image/avatar.jpeg

resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing

external-links:
  linkedin: thomasina-lester
  github:
  stackoverflow:
  medium:
  x-twitter:
  threads:
  instragram:
  youtube:
  discord:
  bluesky:
  
skills:
  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Creo
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)
    - Siemens NX
    - Inventor (Autodesk)
    - CATIA (Dassault Systèmes)
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - SLS
    - DMLS
    - PolyJet Printing
    - Vacuum Casting
    - Laser Cutting
    - Water Jet Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Design Standards / Practices
    tools:
    - GD&T ASME Y14
    - ISO fits and tolerances
    - PLM (PTC Windchill / Arena)   
  - category: PCB Design
    tools:
    - Altium Designer
    - Altium
    - Eagle 
    - KiCad
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Six Sigma methodologies
    - Shain Red-X

colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

#########################################################################################################

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
